[build]
command = "npm run build"
publish = "build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
REACT_APP_OMDB_API_KEY = "e89a743b"

[context.deploy-preview.environment]
REACT_APP_OMDB_API_KEY = "e89a743b"

[context.branch-deploy.environment]
REACT_APP_OMDB_API_KEY = "e89a743b"
